name: AutoBuild

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger BE build
        run: |
          git clone --depth=1 --branch=master https://github.com/squi2rel/Mindustry-CN-ARC-Builds
          cd Mindustry-CN-ARC-Builds
          BNUM=$(($GITHUB_RUN_NUMBER + 50000))
          git tag ${BNUM}
          git config --global user.name "Github Actions"
          git push https://squi2rel:${{ secrets.API_TOKEN_GITHUB_2 }}@github.com/squi2rel/Mindustry-CN-ARC-Builds ${BNUM}
