name: AutoBuild

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger BE build
        run: |
          git clone --depth=1 --branch=master https://github.com/Jackson11500/Mindustry-CN-ARC-Builds
          cd Mindustry-CN-ARC-Builds
          BNUM=$(($GITHUB_RUN_NUMBER + 30000))
          git tag ${BNUM}
          git config --global user.name "Github Actions"
          git push https://Jackson11500:${{ secrets.API_TOKEN_GITHUB_2 }}@github.com/Jackson11500/Mindustry-CN-ARC-Builds ${BNUM}

      - name: Setup fontpack
        uses: actions/checkout@v3
        with:
          ref: ARC-fontpack

      - name: Trigger BE build
        run: |
          git merge master
          git rm rf Mindustry-CN-ARC-Builds
          git clone --depth=1 --branch=ARC-fontpack https://github.com/Jackson11500/Mindustry-CN-ARC-Builds
          cd Mindustry-CN-ARC-Builds
          git tag ${BNUM}
          git config --global user.name "Github Actions"
          git push https://Jackson11500:${{ secrets.API_TOKEN_GITHUB_2 }}@github.com/Jackson11500/Mindustry-CN-ARC-Builds ARC-fontpack ${BNUM}
