name: AutoBuild

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger BE build
        run: |
          git clone --depth=1 --branch=master https://github.com/Jackson11500/Mindustry-CN-ARC-Builds
          cd Mindustry-CN-ARC-Builds
          BNUM=$(($GITHUB_RUN_NUMBER + 30000))
          git tag ${BNUM}
          git config --global user.name "Github Actions"
          git push https://Jackson11500:${{ secrets.API_TOKEN_GITHUB_2 }}@github.com/Jackson11500/Mindustry-CN-ARC-Builds ${BNUM}

      - uses: actions/checkout@v2
      - name: build fontpack build
        run: |
          git switch ARC-fontpack
          git merge master
          git clone --depth=1 --branch=ARC-fontpack https://github.com/Jackson11500/Mindustry-CN-ARC-Builds "ARC-fontpack"
          cd ARC-fontpack
          git tag ${BNUM}
          git config --global user.name "Github Actions"
          git push https://Jackson11500:${{ secrets.API_TOKEN_GITHUB_2 }}@github.com/Jackson11500/Mindustry-CN-ARC-Builds ARC-fontpack ${BNUM}