name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update F-Droid build string
      run: |
        git clone --depth=1 --branch=master https://github.com/RICCJ/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        echo "Updating version to ${RELEASE_VERSION:1}"
        BNUM=$(($GITHUB_RUN_NUMBER + 1000))
        echo versionName=7-fdroid-${RELEASE_VERSION:1}$'\n'versionCode=${BNUM} > version_fdroid.txt
        git add .
        git commit -m "Updating to build ${RELEASE_VERSION:1}"
        git push https://RICCJ:${{ secrets.API_TOKEN_GITHUB }}@github.com/RICCJ/MindustryBuilds
